# This is a basic workflow to help you get started with Actions

name: Check lint error and auto fix (frontend)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  pull_request:
    branches:  [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Setup dependencies
        run: npm ci

      - name: Lint check
        run: npm run fix

      - name: Build
        run: npm run build